ArtEShop.Web/Controllers/ArtPiecesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ArtEShop.Domain.DomainModels;
using ArtEShop.Domain.DTO;
using System.Security.Claims;
using ArtEShop.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;

namespace ArtEShop.Web.Controllers
{
    public class ArtPiecesController : Controller
    {
        private readonly IArtPieceService _artPieceService;
        private readonly IFileService _fileService;

        public ArtPiecesController(IArtPieceService artPieceService, IFileService fileService)
        {
            _artPieceService = artPieceService;
            _fileService = fileService;
        }


        // GET: ArtPieces
        public IActionResult Index(string SearchString)
        {
            FilterArtPiecesDTO model = new FilterArtPiecesDTO();
            if (SearchString.IsNullOrEmpty()) model.ArtPieces = _artPieceService.GetAll();
            else model.ArtPieces = _artPieceService.GetAllByName(SearchString);

            model.SearchString = SearchString.IsNullOrEmpty() ? "" : SearchString;
            return View(model);
        }

        // GET: ArtPieces/Details/5
        public IActionResult Details(Guid id)
        {
            var artPiece = _artPieceService.GetById(id);
            if (artPiece == null)
            {
                return NotFound();
            }

            return View(artPiece);
        }

        public IActionResult Edit(Guid id)
        {
            var artPiece = _artPieceService.GetById(id);
            if (artPiece == null)
            {
                return NotFound();
            }

            return View(artPiece);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArtPiece artPiece)
        {
            _artPieceService.Update(artPiece);
            return RedirectToAction(nameof(Index));
        }

        // GET: ArtPieces/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ArtPieces/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Price,Id,ImageFile")] ArtPieceDTO artPieceDTO)
        {
            if (ModelState.IsValid)
            {
                string[] allowedFileExtentions = [".jpg", ".jpeg", ".png"];
                string createdImageName = await _fileService.SaveFile(artPieceDTO.ImageFile, allowedFileExtentions);

                _artPieceService.Insert(artPieceDTO, createdImageName);
                return RedirectToAction(nameof(Index));
            }

            return View(artPieceDTO);

        }


        public IActionResult ChangeAvailable(Guid id)
        {
            var artPiece = _artPieceService.GetById(id);
            if (artPiece == null)
            {
                return NotFound();
            }
            _artPieceService.ChangeAvailable(artPiece);

            return RedirectToAction(nameof(Index));
        }


        [Authorize]
        public IActionResult AddArtPieceToCart(Guid id)
        {
            AddToCartDTO model = new AddToCartDTO();

            model.ArtPiece = _artPieceService.GetById(id);
            model.Quantity = 1;

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddArtPieceToCart(AddToCartDTO model)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            _artPieceService.AddProductToShoppingCart(model.ArtPiece.Id, Guid.Parse(userId), (int)model.Quantity);

            return RedirectToAction(nameof(Index));
        }

    }
}

ArtEShop.Web/Views/ArtPieces/AddArtPieceToCart.cshtml
@model ArtEShop.Domain.DTO.AddToCartDTO;

<div class="container d-flex justify-content-center align-items-center" style="height:500px;">
    <form method="post" asp-action="AddArtPieceToCart">

        <input type="hidden" asp-for="ArtPiece.Id" class="form-control" />

        <div class="d-flex justify-content-center mt-2 align-items-center" style="width: auto; height: 500px;">
            <img class="card-img-start mt-3 mx-5" src="/uploads/@Model.ArtPiece.Image" style="max-width:500px; height:auto; max-height: 500px; width:auto;" alt="Image for product!">

            <div class="mx-5 d-flex-y align-self-center justify-content-center" style="width:50%;">
                <h3 class="card-title text-center my-3">@Model.ArtPiece.Name</h3>

                <h6 class="text-center mb-3">Price: @Model.ArtPiece.Price ДЕН</h6>
                <div class="d-flex justify-content-center align-items-center" style="width:150px;">
                    <label asp-for="Quantity" class="control-label mx-2"></label>
                    <input required asp-for="Quantity" class="form-control" type="number" min="1" value="1" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                <div class="row mt-4" style="width:150px;">
                    <button type="submit" class="btn btn-success">Add To Cart</button>
                </div>
            </div>
        </div>
        
    </form>

</div>

ArtEShop.Web/Views/ArtPieces/Create.cshtml
@model ArtEShop.Domain.DTO.ArtPieceDTO

@{
    ViewData["Title"] = "Create";
}

<h3>Create Art Piece</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input required asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label mt-2"></label>
                <input required asp-for="Price" class="form-control" type="number" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label mt-2">Image</label>
                <input required type="file" asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-evenly align-items-center mt-4">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArtEShop.Web/Views/ArtPieces/Edit.cshtml
@model ArtEShop.Domain.DomainModels.ArtPiece;

@{
    ViewData["Title"] = "Edit";
}

<h3>Edit Art Piece</h3>

<hr />
<div class="container col-md-4 d-flex justify-content-center align-items-center" style="height: 470px;">
        <img class="card-img-start mt-3 mx-5" src="/uploads/@Model.Image" style="max-width:470px; height:auto; max-height: 470px; width:auto;" alt="Image for product!">

        <form asp-action="Edit" method="post" class="d-flex-y align-self-center justify-content-center" style="width:auto;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="width:200px;">
                <label asp-for="Name" class="control-label mt-2"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label mt-2"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group d-flex justify-content-evenly align-items-center mt-2">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>

ArtEShop.Web/Views/ArtPieces/Index.cshtml
@model ArtEShop.Domain.DTO.FilterArtPiecesDTO
@using ArtEShop.Domain.IdentityModels
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="d-flex w-auto">
        @if(User.IsInRole("Admin"))
        {
            <div class="m-3 float-start">
                <a class="btn btn-success" style="width:200px; margin-left:28px" asp-action="Create">Insert New Product</a>
            </div>
        }
    </div>

    <form asp-action="Index" method="get">
        <div class="form-actions no-color d-flex align-items-center justify-content-center">
                <input class="mx-2 rounded-3 px-2 text-center" type="text" placeholder="Search" name="SearchString" value=@Model.SearchString>
                <div style="position:relative;">
                     <input type="image" src="images/search-icon.jpg" style="height:22px; position:absolute; top:-11px; left:-34px;" alt="Search"/>
                </div>
        </div>
    </form>

    @for (int i = 0; i < Model.ArtPieces.Count; i++)
    {
        var item = Model.ArtPieces[i];

        @if(i%3 == 0)
        {
            @:<div class="row">
        }

        <div class="col-3 m-5">
                <div class="card d-flex flex-column justify-content-between" style="width: 20rem; height: 30rem;">
                    <img class="card-img-top align-self-center mt-4" src="/uploads/@item.Image" style="max-height: 20rem; width:auto; max-width:15rem; height:auto;" alt="Image for product!">
                    <div class="d-flex flex-column justify-content-between">
                        <div class="card-body pt-0">
                           <h3 class="card-title text-center">@item.Name</h3>
                           <h6 class="card-text text-center">Price: @item.Price EUR</h6>
                        </div>
                        <div class="card-footer d-flex justify-content-evenly">
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-controller="ArtPieces" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Edit</a>

                            @if ((bool)item.IsAvailable)
                            {
                                <a asp-controller="ArtPieces" asp-action="ChangeAvailable" asp-route-id="@item.Id" class="btn btn-danger">Make Unavailable</a>
                            } else
                            {
                                <a asp-controller="ArtPieces" asp-action="ChangeAvailable" asp-route-id="@item.Id" class="btn btn-danger">Make Available</a>
                            }
                        } else
                        {
                            @if ((bool)item.IsAvailable)
                            {
                                <a asp-controller="ArtPieces" asp-action="AddArtPieceToCart" asp-route-id="@item.Id" class="btn btn-success">Add to Cart</a>
                            } else
                            {
                                <p>This art is unavailable right now.</p>
                            }
                        }
                       </div>
                    </div>

                    </div>
                    
        </div>

        @if(i%3 == 2) 
        {
            @:</div>    
        }
    }

</div>