ArtEShop.Web/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ArtEShop.Domain.DomainModels;
using ArtEShop.Service.Interface;
using ArtEShop.Domain.DTO;
using System.Security.Claims;

namespace ArtEShop.Web.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IRequestService _requestService;
        private readonly IFileService _fileService;

        public RequestsController(IRequestService requestService, IFileService fileService)
        {
            _requestService = requestService;
            _fileService = fileService;
        }


        // GET: Requests
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(Create));
            }
            HttpClient httpClient = new HttpClient();
            string URL = "";

            if (User.IsInRole("Admin"))
            {
                URL = "https://localhost:44363/api/getallrequests";
                //URL = "https://arteshopweb20250907181936-b6gaf4b3c6h7engd.canadacentral-01.azurewebsites.net/api/getallrequests";

            }
            else
            {
                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                URL = $"https://localhost:44363/api/getalluserrequests/{userEmail}";
                //URL = $"https://arteshopweb20250907181936-b6gaf4b3c6h7engd.canadacentral-01.azurewebsites.net/api/getalluserrequests/{userEmail}";

            }

            HttpResponseMessage message = await httpClient.GetAsync(URL);
            var data = await message.Content.ReadFromJsonAsync<List<Request>>();

            List<RequestDTO> model = new List<RequestDTO>();
            foreach (var item in data)
            {
                model.Add(_requestService.EntityToDTO(item));
            }
            ;

            return View(model);
        }

        // GET: Requests/Details/5
        public IActionResult Details(Guid id)
        {
            var request = _requestService.GetById(id);
            if (request == null)
            {
                return NotFound();
            }

            RequestDTO model = _requestService.EntityToDTO(request);

            return View(model);
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRequestDTO model)
        {
            if (ModelState.IsValid)
            {
                string[] allowedFileExtentions = [".jpg", ".jpeg", ".png"];
                string createdImageName = await _fileService.SaveFile(model.ReferenceImageFile, allowedFileExtentions);
                if (!User.Identity.IsAuthenticated)
                {
                    _requestService.RequestPiece(model, createdImageName);

                    return RedirectToAction("Index", "ArtPieces");

                }
                model.Email = User.FindFirst(ClaimTypes.Email)?.Value;
                _requestService.RequestPiece(model, createdImageName);
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Requests/Edit/5
        public IActionResult Edit(Guid id)
        {
            var request = _requestService.GetById(id);
            if (request == null)
            {
                return NotFound();
            }

            RequestDTO model = _requestService.EntityToDTO(request);

            return View(model);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RequestDTO request)
        {
            if (User.IsInRole("Admin")) _requestService.UpdateFromDTO(request, true);
            else _requestService.UpdateFromDTO(request, false);
            return RedirectToAction(nameof(Index));
        }

    }
}

ArtEShop.Web/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ArtEShop.Domain.DomainModels;
using ArtEShop.Service.Interface;
using System.Security.Claims;
using ArtEShop.Domain.DTO;
using Microsoft.AspNetCore.Authorization;

namespace ArtEShop.Web.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IOrderService _orderService;

        public ShoppingCartsController(IShoppingCartService shoppingCartService, IOrderService orderService)
        {
            _shoppingCartService = shoppingCartService;
            _orderService = orderService;
        }

        // GET: ShoppingCarts
        [Authorize]
        public IActionResult Index()
        {
            if (User.IsInRole("Admin")) return RedirectToAction("Index", "ArtPieces");
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var userShoppingCart = _shoppingCartService.GetByUserIdWithIncludedProducts(Guid.Parse(userId));
            return View(userShoppingCart);
        }

        public IActionResult DeleteShoppingCartItem(Guid id)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var userShoppingCart = _shoppingCartService.GetByUserId(Guid.Parse(userId));
            _shoppingCartService.DeleteItemFromShoppingCart(id, userShoppingCart.Id);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Payment(Guid? id, int price)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

            PaymentDTO model = new PaymentDTO();
            model.Email = userEmail;
            model.ArtPieceId = id;
            model.TotalPrice = price;

            return View(model);
        }

        [HttpPost]
        public IActionResult Payment(PaymentDTO paymentDTO)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            Order order = _orderService.CreateOrder(paymentDTO.ArtPieceId, Guid.Parse(userId));

            _orderService.PayOrder(order);

            return RedirectToAction(nameof(Index));
        }

    }
}

ArtEShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArtEShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArtEShop.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex">
                <div class="float-start">
                    <a class="navbar-brand" asp-area="" asp-controller="ArtPieces" asp-action="Index">
                        <img src="/images/logo.png" style="height:70px;width:70px;"></img>
                    </a>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="ArtPieces" asp-action="Index">Prints</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Requests" asp-action="Index">Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="ShoppingCarts" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2025 - ArtEShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>